version: '3.9'

services:
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./../:/var/www/html
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: elkb
            MYSQL_USER: elkb
            MYSQL_PASSWORD: 123
    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        depends_on:
            - mysql
            - elasticsearch
        working_dir: /var/www/html
        volumes:
            - ./../:/var/www/html
        entrypoint: [ "php", "/var/www/html/artisan" ]
    composer:
        build:
            context: .
            dockerfile: php.dockerfile
        working_dir: /var/www/html
        volumes:
            - ./../:/var/www/html
        entrypoint: [ "composer" ]
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
        environment:
            - node.name=elkb
            - cluster.name=sokanacademy
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - xpack.security.enabled=true
            - ELASTIC_PASSWORD=123
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

